# Environment settings
env:
  name: "sokoban"
  data_dir: "data/sokoban"
  env_kwargs:
    dim_x: 6
    dim_y: 6
    num_boxes: 1
    max_steps: 100
    search_depth: 30 # this will change the starting position of the player